<?php
 $title = 'Agregar Texto';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <?php
 $form->setAttribute('action', $this->url('itext/itext', array('controller' => 'itext', 'action'=>'addItext')));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('ID'));
 echo "<br/>";
 echo $this->formRow($form->get('idf'));
 echo "<br/>";
 echo $this->formRow($form->get('value'));
 echo "<br/>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 