<script src="http://code.jquery.com/jquery-1.12.1.js"></script>
<script src="http://code.responsivevoice.org/responsivevoice.js"></script>

<?php
 $title = 'Agregar Texto';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <?php
 $form->setAttribute('action', $this->url('itext/itext', array('controller' => 'itext', 'action'=>'addItext')));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('ID'));
 echo "<br/>";
 echo $this->formRow($form->get('idf'));
 echo "<br/>";?>
 <textarea type="text" name="value" id="value"></textarea>
 <?php
 //echo $this->formRow($form->get('value'));
 echo "<br/>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?><a href="#" class="say">Escuchar Texto!</a> 
 <audio src="" hidden class=speech></audio> 
 <script> 
	 $("a.say").on('click', function(e){ e.preventDefault();
	  var text = $("textarea[name=value]").val();
	   responsiveVoice.speak(text,"Spanish Female");
	    text=encodeURIComponent(text); var url="http://" }) 
</script> 