

<?php
 $title = 'iText';
 $this->headTitle($title);
 ?>
 
 
 <?php
 $form->setAttribute('action', $this->url('itext/itext', array('controller' => 'itext', 'action'=>'addItext')));
 $form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('ID'));
echo $this->formRow($form->get('idf'));?>
<div align="center">
	<h1><?php echo $this->escapeHtml($title); ?></h1>
	<table>
		
			<tr>
				 <td>
				 	
				 	<?php echo  $this->formRow($form->get('value1')); ?>
				 </td>
			 </tr>
		
		<tr>
			 <td>
			 	<textarea type="text" name="value" id="value" cols="50" rows="10"></textarea>
			 </td>
		</tr>
		<tr>
			<td><?php
				 echo $this->formSubmit($form->get('submit'));
				 echo $this->form()->closeTag();
				 ?>
				 <a href="#" class="say btn btn-success" >Escuchar Texto!</a>
				 <a href="#" class="say1 btn btn-success" >Deletrear Texto!</a> 
				 <audio src="" hidden class=speech></audio>
			</td>
		</tr>
	 </table>
</div> 
 <script> 
	 $("a.say").on('click', function(e){ e.preventDefault();
	  	var text = $("textarea[name=value]").val();
	   	responsiveVoice.speak(text,"UK English Male");
	    text=encodeURIComponent(text); var url="http://" }) 

	$("a.say1").on('click', function(e){ e.preventDefault();
  		var text = $("textarea[name=value]").prop('value');
  		text = text.split('');
  		$.each(text, function(i, item) {        
    	responsiveVoice.speak(item, "Spanish Female");
  		});  
	})
</script> 