

<?php
 $title = 'Escuchar texto';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <?php
 $form->setAttribute('action', $this->url('itext/itext', array('controller' => 'itext', 'action'=>'returnText', 'ID'=> $this->ID)));
 $form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('ID'));
echo $this->formRow($form->get('idf'));?>
<table>
	
		<tr>
			 <td>
			 	<a class="btn btn-info" href="<?php echo $this->url('itext/itext', array('controller' => 'itext', 'action'=>'addItext'));?>">Atras</a>
			 </td>
		 </tr>
	
	<tr>
		 <td>
		 	<textarea type="text" name="value" id="value" cols="50" rows="10"></textarea>
		 </td>
		 <td><?php
			 echo $this->form()->closeTag();
			 ?>
			 <a href="#" class="btn btn-info">Atras</a>
			 <a href="#" class="say btn btn-success" >Escuchar Texto!</a> 
			 <audio src="" hidden class=speech></audio>
		</td>
	</tr>
 </table> 
 <script> 
	 $("a.say").on('click', function(e){ e.preventDefault();
	  var text = $("textarea[name=value]").val();
	   responsiveVoice.speak(text,"Spanish Female");
	    text=encodeURIComponent(text); var url="http://" }) 
</script> 